### ISSUE TITLE
Icons not shipping with package

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#105]
### Describe the Bug

_A clear and concise description of what the bug is._

Small icons (and the CDP icon) aren't shipping with the package.

### Reproduction

_Steps to reproduce the behavior:_

1. Go to https://councildataproject.org/seattle-staging/#/
2. Click on 'Advanced Options'
3. Click on 'Date'

### Expected Behavior

_A clear and concise description of what you expected to happen._

Icons should ship and display in generated app

### Screenshots

_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/17132317/137009519-dfac9e1b-6168-475b-8e7b-c5ea4c4e5e84.png)

### Environment

_Any additional information about your environment._

-   OS Version: _[e.g. macOS 11.3.1]_ Ubuntu 20.04
-   Browser Version: _[e.g. Chrome 89.0]_ Firefox 93
-   CDP Frontend Version: _[e.g. 0.5.0]_ 0.4.3: https://github.com/CouncilDataProject/seattle-staging/blob/main/web/package.json#L13

**Comment by tohuynh** [comment]
I will work on this.
