### ISSUE TITLE
Adopt Mozilla Protocol wherever possible

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#11]
## Use Case
*Please provide a use case to help us understand your request in context*

Offload some of the design and styling maintainence work while also having nice standardize, accessible design.

## Solution
*Please describe your ideal solution*

[Mozilla protocol](https://protocol.mozilla.org/) is a really good solution. Both because I have long been a fan of Mozilla styling but also because of how easy it is to use (imo).

This doesn't mean scrap all the UX design work already done. I think we should simply merge the two.

For example, instead of writing our own cards, we can simply use [theirs](https://protocol.mozilla.org/patterns/molecules/card.html#extra-small-card) but add all the extra stuff we need. I.E. tags, etc.

Also see: [Mozilla branding style guide](https://mozilla.design/mozilla/) for great examples and quick rundown of their choices.

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by hawkticehurst** [comment]
Based on our conversation from last night I'm going to go ahead and assign this issue to myself!
