### ISSUE TITLE
Hightlight found gram in context span on event card and pass the found gram to the transcript search when card is clicked / user navigates to event page

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#123]
### Feature Description

Highlight the search query in excerpt/context span of an event card (and maybe legislation cards too)

### Use Case

Highlighting the search query would provide a visual cue as to why these search results are relevant.

### Solution

Use the already installed [react-highligt-words](https://github.com/bvaughn/react-highlight-words) .

Example of the use: https://github.com/CouncilDataProject/cdp-frontend/blob/main/src/components/Details/TranscriptItem/TranscriptItem.tsx#L138

### Screenshots/References
![image](https://user-images.githubusercontent.com/37560480/144170155-7ef05da1-d903-4c07-a307-50ef027858e4.png)

For example, any mention of "rent control" should be highlighted in the excerpt/context span portion of the cards.

cc @JacksonMaxfield  for thoughts.

**Comment by JacksonMaxfield** [comment]
It should be the gram from the context span. "rent control" doesn't appear in the first example but "rent" does for example. I think the returned search results should have which gram is contained in the context span... the problem may be in punctuation and such.

Likely will need to do a regex that ignores punctuation and casing?

**Comment by tohuynh** [comment]
So, we would highlight "rent" in the first card?

> Likely will need to do a regex that ignores punctuation and casing?

Yeah, I think there are options for this.

**Comment by JacksonMaxfield** [comment]
> So, we would highlight "rent" in the first card?

Yes. The search results _should_ have a field for "which gram is contained in the context span" which should make it easier but not entirely sure.

**Comment by JacksonMaxfield** [comment]
Correction, the search results currently do not have a field for "which gram is in the context span" but should be decently easy to add it: https://github.com/CouncilDataProject/cdp-frontend/blob/main/src/networking/EventSearchService.ts#L196

**Comment by JacksonMaxfield** [comment]
Also: add back in that when you click on an search result, it will prepopulate the "search transcript" container with the query / actually better because we store the "found grams" of the search, it will prepopulate that container with the gram with the highest value.

**Comment by tohuynh** [comment]
Wait, populate the search transcript container with the user query or the gram with the highest value?

**Comment by JacksonMaxfield** [comment]
> Wait, populate the search transcript container with the user query or the gram with the highest value?

Idk this is tricky.

I remember that a common occurance on v2 was that the search query matched because a unigram matched but not the whole query and so you would click an event and nothing would show up in the transcript for what matched

So I was trying to combat that a bit by saying "use whatever gram was found as part of the context span selection" to pass along to the event page / transcript search so that we are guarenteed a match.

I guess the dream but out of the scope of this issue would be to allow for multi-term search in the transcript, comma separated?

`events/:id/?q="rent,control,rent%20;control"` or something?

and all of the matching grams are passed and used for search through the transcript and matching sentences are found.

**Comment by tohuynh** [comment]
I will pass the user query or highest gram via location.state, so no need for ?q.

The searching in "search transcript" is a substring matching. So if the query is "transportation utilities", it will return only transcript items that has exactly that query (ignoring case).

**Comment by JacksonMaxfield** [comment]
> I will pass the user query or highest gram via location.state, so no need for ?q.

Yea for now I would choose highest gram. and location.state makes sense.

> The searching in "search transcript" is a substring matching. So if the query is "transportation utilities", it will return only transcript items that has exactly that query (ignoring case).

Sounds good.

**Comment by tohuynh** [comment]
what gets highlighted in "search transcript" is a little different. It will highlight anything that matches the query. e.g. if the query is "transportation utilities", it will highlight that and also any other appearance "transportation" or "utilities" in that sentence.

**Comment by JacksonMaxfield** [comment]
> what gets highlighted in "search transcript" is a little different. It will highlight anything that matches the query. e.g. if the query is "transportation utilities", it will highlight that and also any other appearances of "transportation" or "utilities" in that sentence.

Oh perfect. So it does the n-gram splitting. Then great. Just use the search query. No need for passing the highest gram.

**Comment by tohuynh** [comment]
https://github.com/CouncilDataProject/cdp-frontend/blob/main/src/components/Details/TranscriptItem/TranscriptItem.tsx#L139

Sort of. I split the query using whitespace into a list of tokens and let react-highlights-words highlight anything in that list of token.

**Comment by JacksonMaxfield** [comment]
https://user-images.githubusercontent.com/17132317/144356779-a9a0d124-3329-4d9f-9723-6122e440a707.mp4

**Comment by tohuynh** [comment]
I think I will go with the first option. Highlighting the gram in the card and then populating the gram in "search transcript" has a nice continuity.
