### ISSUE TITLE
Minutes Item expansion cleanup

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#126]
1. Remove the minutes item arrow right: 
![image](https://user-images.githubusercontent.com/17132317/144351693-9ae133c2-df46-49ac-a3b8-f0c1af48c45a.png)

We have a plus sign, no need for the arrow as well.

2. Why is the "See documents" split across two lines?

3. If the minutes item has a description, we should display description before all of the attachments. I hacked this into the html of the page but here is a rough example:

![image](https://user-images.githubusercontent.com/17132317/144351997-c7f24be0-148d-41ec-ace2-bd05d80b4e09.png)

4. All links should be made to open in tab instead of redirecting from the current CDP page.

**Comment by tohuynh** [comment]
To clarify the picture, the "description" is a sibling of "See documents" and should appear immediately below the minutes item title (e.g. CB 120230). The "See documents" is supposed to toggle the visibility of the document links.

**Comment by JacksonMaxfield** [comment]
> To clarify the picture, the "description" is a sibling of "See documents" and should appear immediately below the minutes item title (e.g. CB 120230). The "See documents" is supposed to toggle the visibility of the attachment links.

That's a good question. When I hacked that into the HTML I actually put it as a child of the toggle-able div or w.e. -- the description was only shown when the dropdown was expanded.

But I think with some better white spacing it would be better to always show it.

**Comment by tohuynh** [comment]
The structure should be something like this?
<div>minutes item title</div>
<div>description</div>
<details>
    <summary>See documents</summary>
    <ul>
       <li>attachment 1</li>
       <li>attachment 2</li>
    </ul>
</details>

```
<div>minutes item title</div>
<div>description</div>
<details>
    <summary>See documents</summary>
    <ul>
       <li>attachment 1</li>
       <li>attachment 2</li>
    </ul>
</details>

```

**Comment by JacksonMaxfield** [comment]
Yes I think that would be best.
