### ISSUE TITLE
Create exportable App to import into cookiecutter

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#13]
## Use Case
*Please provide a use case to help us understand your request in context*

Get started on the full exportable app that this library is ultimately responsible for.

## Solution
*Please describe your ideal solution*

Thinking out loud:
A app that a cookiecutter instance can import from the library. Notably I have two initial ideas as to what it may be good to parametrize but willing to hear other thoughts.

1. `instance.css` a css file that contains color definitions, i.e. `primary`, `secondary`, `underline`, `highlight`, etc. Not sure how many colors we will have customizable in the app itself but just the general idea that some of the styling in an instance is customizable.
2. `instance.json` a JSON file that stores metadata for the web app to use, i.e. links to the official government sources, etc. Again, not sure how much we will need in this config but there is an assumption that it will be used.

Ultimately it would great if the end result of this specific issue was for the [cookiecutter-cdp-deployment](https://github.com/councildataproject/cookiecutter-cdp-deployment) to import the `CDPApp` (or w.e. name we go with) into it and for that app to render a header, general landing page, and footer. The footer content can be filled with the content of the `instance.json` and maybe some of the content on the landing page can be colored using the `instance.css`.

## Additional Notes
Please keep in mind the desire to move to Mozilla styling as per #11 but here is the mock landing page from UX team:
![image](https://user-images.githubusercontent.com/17132317/99162164-86f0ea80-26af-11eb-8bf9-d6d832e8ec8e.png)

This was inspired from [ZocDoc](https://www.zocdoc.com/), but would again would _personally_ prefer and side on a mix of this and Mozilla styling.

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by hawkticehurst** [comment]
Here to add some thoughts to the discussion!

I really like and am in support of the idea of having some kind of config CSS and JSON files to make setting up the app a lot easier and give some customization options. I definitely think it's an avenue worth pursuing.

A clarifying question however is where these files should be created and referenced from? 

To be more specific, if one of the end goals is to be able to create an NPM package that exports some kind of App initialization function which cookie-cutter can then import and use, I think it would be really nice from a usability perspective to have either:

- The config files themselves be parameters of this init function, and/or
- Objects which contain style and metadata information that can override default config files be parameters of the init function.

This in my mind allows someone creating a new instance of CDP to only have to work within the context of the cookie-cutter tool and never have to dive into the `cdp-instance` repo.

Not sure if this was already an idea you were thinking about or if I'm not considering some important details, but let me know what you think!

**Comment by JacksonMaxfield** [comment]
This is definitely the direction I was headed in my thinking but a bit more fleshed out!

I would say config files that override defaul styles and values. I think passed in during init? I don't know what the "standard" is in JS to do that. I.E. passing a filename to an App vs just having the in the correct location in the web app directory.

This is where I defer to @tohuynh a lot of the time since I don't know JS best practices. But I would assume that having them just be files in the generated repo that the exported App picks up due to proper location and name is better than a sort of an `init` parameter like in Python.

I would say in _general_, yes the `cookiecutter` could do a lot of the heavy lifting here but I wouldn't be too afraid of just informing the user that they should go edit those files if they feel the desire to because they, by requirement, must edit the Python `get_events` function. I imagine that at the end of the cookiecutter process is a print statement that says:

> Please fill in the required `python/get_events.py` Python script and optionally edit the `web/instance.css` styling and `web/instance.json` config file.

**Comment by tohuynh** [comment]
I think config files are fine. For customized styling, we could have the cookiecutter create a `web/instance.css`  that users can edit. We can have CSS variables defined in `web/instance.css` and then use those variables throughout the App in `cdp-instance`

**Comment by JacksonMaxfield** [comment]
That is I think exactly what I was ultimately getting to. Have the defaults be placed in the cookiecutter template that the user can then edit to whatever they would like.

**Comment by tohuynh** [comment]
Not entirely sure what would go in `web/instance.json`, but the firestore_connection_url is needed.
We can write something like in App.js created by the cookiecutter:
```
import CDPInstance, { createReduxStore } from "@councildataproject/cdp-instance;
```

Then use two things to create the App in App.js
