### ISSUE TITLE
Add jumped to sentence visual cue

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#133]
When using the "jump to sentence in the full transcript" feature on the event page, my eyes have a hard time finding the sentence in the full transcript.

Add some sort of visual cue to the jumped to sentence so that the user would have an easier time finding the sentence in the full transcript.

Visual cue options:
- Some sort of border around the transcript item
- Focus the play video button of transcript item

cc @JacksonMaxfield for additional thoughts

**Comment by JacksonMaxfield** [comment]
Strong agree on this. I was struggling with this just yesterday.

My suggestion would be maybe like a border-left with one of the brighter colors from cdp-design that fades out after a few seconds?

Border bottom would likely feel odd visually but a left side border wouldn't get in the way but would still indicate something.

**Comment by tohuynh** [comment]
> My suggestion would be maybe like a border-left with one of the brighter colors from cdp-design that fades out after a few seconds?

I like this suggestion the most so far.
