### ISSUE TITLE
Add disclaimer about ML generated transcription to event search results page

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-frontend#141]
We have known there will always be _some_ transcription errors and until we invest in making our own model, we should at the very least put a disclaimer about them:

> To provide event transcripts at low-cost, Council Data Project uses [Google Speech-to-Text](https://cloud.google.com/speech-to-text). The transcriptions may include errors and absurdities. Please understand that our team regrets any miscommunication caused by these errors.

**Comment by smai-f** [comment]
Hey @JacksonMaxfield , is anyone working on this, and if not, can I pick it up? Mark is in contact with our city about our CDP instance and I think it'd be good to have this disclaimer since all of our transcripts are ML generated.

**Comment by JacksonMaxfield** [comment]
To my knowledge no one is working on this! Feel free to take it on.

Totally agree that it's a good thing to have haha. Where to put it on the single event page / maybe search page too is the question in my mind.

**Comment by smai-f** [comment]
@JacksonMaxfield Cool, I'll try a few placements out and see what y'all think!

**Comment by JacksonMaxfield** [comment]
Wooo! Thanks!

**Comment by Shak2000** [comment]
I made a prototype of a few options, and I want to get early feedback:

1. In the transcript: https://drive.google.com/file/d/1S9pE5ItALlGTng8BQiE0CFX2lmsy4vYl/view?usp=sharing
2. In the search page: https://drive.google.com/file/d/1kQCa10g3FSBmdl5ogtniRU71uy-yopDf/view?usp=sharing

I can add a box around the text, color the text, or change the font size. I can also put the text below the meetings.

For now, the text is displayed for all results. Once we decide how to display the text, I will how to filter it only for ML classifications. I think that classification can only work for the first option since we have too many events in the second option—some of them can be ML-generated, others can be human-generated.

I am open to receiving any advice.

**Comment by evamaxfield** [comment]
Hey @Shak2000 these look good, I have one suggestion but before I get to it, I am curious if you can try deploying: https://github.com/CouncilDataProject/cdp-frontend/blob/main/CONTRIBUTING.md#deploying-your-storybook-docs-site-or-example-app

Specifically:
```bash
npm run build:app
npm run deploy:app
```

Then we can simply go to your page and check it out.

**Comment by Shak2000** [comment]
Here it is: https://shak2000.github.io/cdp-frontend/#/

**Comment by evamaxfield** [comment]
Thanks! I think I like the event search results location more than the transcript search results location.

Feel free to remove the transcript search results one.

I am tempted to ask to also place this in the footer so it's always present.

**Comment by evamaxfield** [comment]
I may have some general rewording later

**Comment by Shak2000** [comment]
I removed the transcript search location. I added the footer. I put the footer where the copyrights. I can move it into the links in the area above

**Comment by evamaxfield** [comment]
> I removed the transcript search location. I added the footer. I put the footer where the copyrights. I can move it into the links in the area above

Wanna open a PR?

Four things:
1. for the text on the event search results page: can you make the font size smaller? It is currently rendered at 1.125 rem it looks like. I think 1 rem looks better personally
2. for the text on the event search results page: can you change it to: "To provide event transcripts at low-cost, Council Data Project uses Google Speech-to-Text for transcription. Event transcripts may include errors."
3. for the text on the event search results page: can you move the disclaimer to below the body + date filters and the sort options?
4. for the text in the footer: can you change it to: "In many cases, Council Data Project utilizes a fine-tuned Google Speech-to-Text model for generation of event transcripts. We understand that transcripts may include errors. If you are a machine learning expert and wish to help improve our system for generating transcripts, please reach out to us on GitHub."

**Comment by Shak2000** [comment]
I implemented all of the requests

**Comment by Shak2000** [comment]
Can you please assign it to me? I have a PR waiting
