### ISSUE TITLE
Webpages failing

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#143]
### Describe the Bug

_A clear and concise description of what the bug is._

Unsure: `TypeError: e[0] is undefined`

### Reproduction

_Steps to reproduce the behavior:_

1. Go to http://councildataproject.org/seattle-staging/#/events/9409f4d1ea09 (or http://councildataproject.org/seattle-staging/#/events/c46c534afdce or http://councildataproject.org/seattle-staging/#/events/da2b5f47e912)
2. See error

### Expected Behavior

_A clear and concise description of what you expected to happen._

The page loads

### Screenshots

_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/17132317/146116687-12530d67-8028-4b3c-b7e0-ab62651c1dfb.png)

### Environment

_Any additional information about your environment._

-   OS Version: _[e.g. macOS 11.3.1]_ Ubuntu 20.04
-   Browser Version: _[e.g. Chrome 89.0]_ Firefox v95.0
-   CDP Frontend Version: _[e.g. 0.5.0]_ v3.0.0

**Comment by tohuynh** [comment]
The database returned two sessions for http://councildataproject.org/seattle-staging/#/events/9409f4d1ea09 (I don't think it should. The two sessions look the same to me). As a result, no transcript json was found for the second session.

**Comment by tohuynh** [comment]
It's the same for the other two events. Two sessions with similar data, except for the id. And no transcript json for one of the sessions.

**Comment by tohuynh** [comment]
Something to do with this: https://github.com/CouncilDataProject/cdp-scrapers/issues/50 ?

**Comment by JacksonMaxfield** [comment]
Interestingly.... I think the "bug" was that we released a new version. From cdp-backend v3.0.0.dev27 to v3.0.0... And all of those meetings are around the Dec 1 / Dec 2 date of v3 release.

**Comment by JacksonMaxfield** [comment]
Errr correction those meetings _aren't_ around those dates but they have two transcripts of different versions.

**Comment by JacksonMaxfield** [comment]
I think I have found the bug. Has to do with the id generator / hasher
