### ISSUE TITLE
Invalid Heading Order on Person Page

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#152]
1. Go to PersonPage in Storybook on a non-mobile size monitor.
2. Observe that Storybook is giving you an accessibility warning.

### Expected Behavior

No warnings from Storybook.  
Suggested fix:
The problem is a invalid heading order h3 -> h4 -> h6(headings of table).
you can fix by changing the table heading to h5 and using different sizes on the heading via https://protocol.mozilla.org/patterns/atoms/typographic.html#heading-elements
mzp-u-title-xs 

### Environment

All non-mobile screens for PersonFullView.

**Comment by tohuynh** [comment]
I changed my mind regarding the suggested fix. For the page title(person name) we should use `h1` with CSS class `mzp-u-title-xs`.  And don't use headings (h1-h6) for the table headers. Instead use `fontweight` and `font-size` to change the table header's appearance.
