### ISSUE TITLE
Person Views' Pictures

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#153]
### Describe the Bug

PersonPage is not receiving the correct data to render the person's picture.  It is not receiving the seat picture either.

### Reproduction

_Steps to reproduce the behavior:_

1. Go to PersonPage on a mobile- or tablet-sized screen.
2. You will never see a person's picture or seat picture. 

### Fix

The person's picture isn't showing up because person.picture.uri is not a valid value for img.src. The download URL is needed instead. See https://github.com/CouncilDataProject/cdp-frontend/blob/main/src/networking/EventSearchService.ts#L255 for an example. 

To get the seatPictureSrc to display, we need the download URL of the seat.image.uri, same solution as for the person picture.

**Comment by tohuynh** [comment]
I can take this one
