### ISSUE TITLE
Voting tables are not rendering all the data

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#155]
### Describe the Bug

Voting tables are not rendering all the data. 

In the person's page, `Meeting` have no data displayed and `Council Decision` should be these [constants](https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/database/constants.py#L10) -- Passed or Failed
![image](https://user-images.githubusercontent.com/37560480/147725109-cb3c4ebd-5103-4f19-a066-a331ff5dec0c.png)

Similarly, in the `Votes` tab of the the event page, the `Council Decision` column should have value Passed or Failed
![image](https://user-images.githubusercontent.com/37560480/147725474-75c0ca31-d546-41c2-b9bc-26a78143db62.png)
(side note: These legislation descriptions can be too long for a cell, we should use top 5 keywords or topics to describe the legislation instead)

**Comment by JacksonMaxfield** [comment]
I think I just reported this same issue in Slack!

> (side note: These legislation descriptions can be too long for a cell, we should use top 5 keywords or topics to describe the legislation instead)

Can't be done until matter index pipeline is done but i do really like this idea!
