### ISSUE TITLE
Biography Fails when Deals with a Person without a Current Role

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#158]
### Describe the Bug

When a Person does not have a current role, the PersonPage either crashes or has other problems.  I have an incoming PR that will fix the crashes, but the problems with the biography having a bunch of undefined stuff remains.

### Reproduction

_Steps to reproduce the behavior:_

1. Go to the People Page
2. Click on Daniel Strauss
3. See bad biography (due to not holding any current role I think?)

Instead of 

### Screenshots

![Screen Shot 2021-12-31 at 5 25 10 PM](https://user-images.githubusercontent.com/9027758/147842221-85c7fd47-bba5-4df9-a52f-8b8c57d473fb.png)

**Comment by tohuynh** [comment]
There are two Dan/Daniel Strauss (the same person). See https://github.com/CouncilDataProject/cdp-backend/issues/146

I think we should just throw an error and show the error page if the page doesn't have the required data.
