### ISSUE TITLE
Allow the `/people/:id` page to render before person's votes and/or biography data is fetched.

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#166]
### Feature Description

_A clear and concise description of the feature you're requesting._

Similar to #101.
Allow the `/people/:id`page  to render before a person's votes and/or biography data is fetched. Depending on how fast the request for biography data is fulfilled, we might need to lazy load the biography data too.

### Use Case

_Please provide a use case to help us understand your request in context._

Reduce the page's "time to interactivity".  Users don't need to see a person's votes right away.

### Solution

_Please describe your ideal solution._

Only load things as they come in. I.e. Maybe the voting table sections show a "Fetching votes..." line until they have returned?

See /src/pages/EventPage for starting point.

**Comment by JacksonMaxfield** [comment]
Neha (UX designer working on legislation page) had a nice idea of putting stuff below the fold and only rendering / fetching when clicked.

![image](https://user-images.githubusercontent.com/17132317/148819757-40fc5526-3670-4a9d-8247-da6e3b61c8f6.png)

The "History" portion of the page is collapsed on first load and background loaded. Data is revealed when accordion is opened. We may be able to do the same thing with the votes.

**Comment by tohuynh** [comment]
Seems like a good idea. Would be good to have consistent UI across pages.
