### ISSUE TITLE
Link event minutes items (that has a matter) to the matter page

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#167]
### Feature Description

_A clear and concise description of the feature you're requesting._
Under the Minutes/Agenda tab of the event page, there is a list of event minutes items that can have a reference to a matter.

### Use Case

_Please provide a use case to help us understand your request in context._
Create a link to the matter page to make navigation easier.

![image](https://user-images.githubusercontent.com/37560480/148820749-d8647122-f3ca-4b07-9c5b-0de5366e2d34.png)
For example, list item 10 will be a link to the matter page.

cc @JacksonMaxfield for additional thoughts

This isn't quite ready for dev as we don't have the matter page yet.

### Solution

_Please describe your ideal solution._

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

### Screenshots/References

_In the case of a visually oriented feature or component request, providing drawings, screenshots, and/or links to examples of what you're seeking will be very helpful._

**Comment by JacksonMaxfield** [comment]
Absolutely agree on this. I would put a link next to the title so something like "10. 2021-0255 > Full Matter Details" or something.
