### ISSUE TITLE
Change matter/legislation description to a list of keywords/topics

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#168]
### Feature Description

In the event page's voting tab,
![image](https://user-images.githubusercontent.com/37560480/147725474-75c0ca31-d546-41c2-b9bc-26a78143db62.png)
These legislation descriptions can be too long for a cell, we should use top 5 keywords or topics to describe the legislation instead.

### Use Case

_Please provide a use case to help us understand your request in context._

The list of keywords/topics is more concise and is better looking overall in the table than the long description

### Solution

_Please describe your ideal solution._
This isn't ready for dev as the matter index pipeline isn't ready

> Can't be done until matter index pipeline is done but i do really like this idea!

_Originally posted by @JacksonMaxfield in https://github.com/CouncilDataProject/cdp-frontend/issues/155#issuecomment-1007030842_
### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

### Screenshots/References

_In the case of a visually oriented feature or component request, providing drawings, screenshots, and/or links to examples of what you're seeking will be very helpful._

**Comment by JacksonMaxfield** [comment]
As a temporary work-around we might just want to cut it off after some number of characters? 512 characters and then `...`?

**Comment by tohuynh** [comment]
Yes, that could work as a temporary fix.
