### ISSUE TITLE
[f_legislationtracking] Legislation introduction component

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#172]
Implement the Legislation introduction component of the legislation details page (`/matters/:id`).

See the figma lofi mocks ups https://www.figma.com/file/VPeHF2SVDn6FneLLl9bihB/Legislation-Tracking-(CDP)?node-id=137%3A350
![image](https://user-images.githubusercontent.com/37560480/149585290-891cf63c-b056-4728-9b82-034856d3dcdc.png)

- The legislation name (e.g. CB 120237) should use an `h1` with `className=mzp-u-title-sm`
- The bill status(In committee) should use `MATTER_STATUS_DECISION` constant and the corresponding icons. The three icons are Adopted, Rejected, In Progress.
- @JacksonMaxfield After the bill status, are we going to display a list of topics(we don't have this data?) or keywords(we will have this data after the matter index pipeline) ?

**Comment by JacksonMaxfield** [comment]
> * @JacksonMaxfield After the bill status, are we going to display a list of topics(we don't have this data?) or keywords(we will have this data after the matter index pipeline) ?

I can get started on a minutes item index pipeline this weekend probably which will give us keywords.
