### ISSUE TITLE
[f_legislationtrackig] Legislation overview component

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#173]
Implement the legislation overview component for the legislation details page (`/matters/:id`)

See the figma lofi mocks ups https://www.figma.com/file/VPeHF2SVDn6FneLLl9bihB/Legislation-Tracking-(CDP)?node-id=137%3A350
![image](https://user-images.githubusercontent.com/37560480/149585705-ab6b7461-8004-48ae-8b3b-f908a61591d1.png)

- Change Bill Overview to Legislation Overview or just Overview
- For the bill status @JacksonMaxfield do we want something more specific than our `MATTER_STATUS_DECISION` constants?

**Comment by JacksonMaxfield** [comment]
I say for now just use the constants. It's the best we have for now. We can add more constants later if we want more granularity.
