### ISSUE TITLE
Parameterize governing body on HomePage component

### ISSUE THREAD

**Issue by isaacna** [CouncilDataProject/cdp-frontend#180]
### Describe the Bug

The home page [always displays](https://github.com/CouncilDataProject/cdp-frontend/blob/main/src/pages/HomePage/HomePage.tsx#L32) "Search City Council" regardless of what the governing body is. This could be inconsistent if the governing [body type chosen in cookiecutter](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/blob/main/%7B%7B%20cookiecutter.hosting_github_repo_name%20%7D%7D/cookiecutter.yaml#L3) is something else. 

This could probably be done by passing cookiecutter variable `governing_body_type` in the [app config](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/blob/main/%7B%7B%20cookiecutter.hosting_github_repo_name%20%7D%7D/web/src/index.jsx#L7-L18) and using it in the react component. I'm not sure if getting the correct localized string based on this would be tricky or simple.

Once this is updated, we'd also have to adjust the config accordingly in cookiecutter-cdp-deployment

### Reproduction

Launch a deployment with CDP with a different governing body type and check the home page.

### Expected Behavior

The message should display something like "Search <governing_body_type>" where the `governing_body_type` is taken from the app config. 

### Screenshots

<img width="931" alt="Screen Shot 2022-01-18 at 4 15 50 PM" src="https://user-images.githubusercontent.com/20964645/150039553-4276a830-ad8e-4378-aa8b-00a5a3fec53a.png">

**Comment by tohuynh** [comment]
> I'm not sure if getting the correct localized string based on this would be tricky or simple.

What other governing body types are there besides "city council" and "county council"? If they are similar then it's relatively simple to localize.

**Comment by JacksonMaxfield** [comment]
https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/infrastructure/cdp_stack.py#L16

**Comment by JacksonMaxfield** [comment]
Yet more reason to have a repo of db models and db constants that builds into a python and JS package :(

**Comment by tohuynh** [comment]
> "Search <governing_body_type>"

👍 

But the entire string has to be localized. We would just have keys in LocalizedStrings.tsx like:
- `search_city_council`: `<actual translation>`
- `search_county_council`: `<actual translation>`

"Search Other" sounds odd though

**Comment by JacksonMaxfield** [comment]
If it's "other" lets just default to something like "search archives" or something?

**Comment by tohuynh** [comment]
The municipality name also sounds good to me

**Comment by JacksonMaxfield** [comment]
Why not: "Search {muni name} archives" then. Make a _bit_ more muni specific while still making it clear what you are searching.

**Comment by tohuynh** [comment]
"Search {muni name} archives" overall? Not sure about "archives" (don't have an opinion on it, willing to majority win).

**Comment by JacksonMaxfield** [comment]
> "Search {muni name} archives" overall? Not sure about "archives" (don't have an opinion on it, willing to majority win).

Fair. I know we are wanting to do more than simply be an archive lookup so that is truly a good point. Muni name is fine for now then.
