### ISSUE TITLE
[f_legislationtracking] Update legislation card

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#188]
Based on design by Neha, update the current legislation card

![image](https://user-images.githubusercontent.com/37560480/151095100-48c8f6e0-432a-4c10-843b-bf5313e3e7a0.png)

- Move the status icon to the left of the status text (consider making the green color darker)
- Add an excerpt to the card, that is either the `matter.title` or search context span. See the similar excerpt in [event card](https://councildataproject.org/cdp-frontend/?path=/story/library-cards-event--meeting-search-result)

**Comment by tohuynh** [comment]
Green color : #005e5e

**Comment by tohuynh** [comment]
cc @JacksonMaxfield We are changing the adopted icon color to #005e5e (Mozilla Protocol Green 80) because the old green doesn't have enough contrast with the white background.

**Comment by JacksonMaxfield** [comment]
Makes sense to me!
