### ISSUE TITLE
Transcript search card and viewer for the event detail page

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#2]
See this: https://projects.invisionapp.com/share/UGW7LLV87VQ#/screens/407317058

**Comment by JacksonMaxfield** [comment]
Example: 
![image](https://user-images.githubusercontent.com/17132317/99860814-0fa4d600-2b49-11eb-8e80-0065cf4351a5.png)

**Comment by JacksonMaxfield** [comment]
The transcript search card will likely be an individual component where the transcript search will be a container that comes later.
