### ISSUE TITLE
`matter.title` is too long sometimes

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#231]
### Feature Description

_A clear and concise description of the feature you're requesting._
Shorten the display of `matter.title` throughout the app.

### Use Case

_Please provide a use case to help us understand your request in context._
Long `matter.title` creates a wall of text that is not user-friendly.

### Solution

_Please describe your ideal solution._
Create a general component that clips the display of content if the content is too large. Then on hover, the user would be able to see the full content.

### Possible implementation
Use [`useRef` and `useEffect` ](https://github.com/QualitativeDataRepository/AnnoREP-Frontend/blob/main/features/ati/AtiManuscript/DatasourceModal/Datasource.tsx#L10)to figure out if the content is too large.

Then use [CSS](https://github.com/QualitativeDataRepository/AnnoREP-Frontend/blob/main/features/ati/AtiManuscript/DatasourceModal/Datasource.module.css) to set the min-width or min-height and hide overflowing content. 

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

### Screenshots/References

_In the case of a visually oriented feature or component request, providing drawings, screenshots, and/or links to examples of what you're seeking will be very helpful._

![image](https://user-images.githubusercontent.com/37560480/173441403-65daa88f-a020-4c0d-89d3-c537365ed111.png)

**Comment by JacksonMaxfield** [comment]
Could you also handle this with css trickery? First 100 characters are bolded then next are normal text or something? Or show the first 100 character then a "show more" thingy?
