### ISSUE TITLE
Correct Disclaimer Text

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#264]
### Describe the Bug

There are few cases of text like this: "In many cases, Council Data Project utilizes a fine-tuned [Google Speech-to-Text](https://cloud.google.com/speech-to-text) model for generation of event transcripts. We understand that transcripts may include errors. If you are a machine learning expert and wish to help improve our system for generating transcripts, please reach out to us on GitHub."

### Expected Behavior

That should be updated to say OpenAI's Whisper Speech-to-Text Model. 

Also we can now specify the word-error-rate as generally between 3.2% and 9%.

**Comment by jonlin14** [comment]
I think the only other one is in the Search Events

"To provide event transcripts at low-cost, Council Data Project uses Google Speech-to-text for transcription. Event transcripts may include errors."

How do we feel about changing them to 

In many cases, Council Data Project utilizes a fine-tuned [OpenAI Whisper Speech-to-Text](https://openai.com/research/whisper) model for generation of event transcripts. The word-error-rate is generally between 3.2% to 9% and as such transcripts may include errors. If you are a machine learning expert and wish to help improve our system for generating transcripts, please reach out to us on GitHub."

and

To provide event transcripts at low-cost, Council Data Project uses [OpenAI's Whisper Speech-to-Text](https://openai.com/research/whisper) for transcription. The word-error-rate is generally between 3.2% to 9% and as such transcripts may include errors.

**Comment by evamaxfield** [comment]
Generally works, but I think its almost too descriptive?

What about:

> Council Data Project utilizes [OpenAI's Whisper Speech-to-Text Model](https://openai.com/research/whisper) model for generation of event transcripts. The produced transcripts may include errors. If you are a machine learning expert and wish to help improve our systems for generating transcripts (or something else!), please reach out to us on GitHub."

and for the banner on the events page:

> Council Data Project utilizes [OpenAI's Whisper Speech-to-Text Model](https://openai.com/research/whisper) model for generation of event transcripts. The produced transcripts may include errors.

I am tempted to link to their paper, specifically linking the "include errors" bit with: https://cdn.openai.com/papers/whisper.pdf

sadly I cant link to the specific appendix table of longform transcription but I think it's okay
