### ISSUE TITLE
Programmatically Create Image Alt Text For Committee Card Photos

### ISSUE THREAD

**Issue by hawkticehurst** [CouncilDataProject/cdp-frontend#27]
## Use Case
To remain accessible we need to add descriptive image alt text to all our card component images, which means at some point we are going to have to figure out how to programmatically label/describe the screenshots we use for each card we generate.

## Solution
My naive thought would be to use some kind of image recognition library to label each of the photos and then use that label as our alt text for each image.

With that said, @JacksonMaxfield says this should be very possible to do, so maybe he can add a comment with some of his ideas.

## Alternatives
In the meantime, we could probably include a less descriptive filler alt text on all the screenshots for each card, but striving to have descriptive alt text for each image is something I think is worth pursuing.

**Comment by JacksonMaxfield** [comment]
Going to close this. I think having some / the same default alt text for all photos (as we do now) is fine for now and if we were to programmatically generate this I would probably do it in Python and store in the database.
