### ISSUE TITLE
Council member's voting records table

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#33]
Pls see: https://projects.invisionapp.com/share/UGW7LLV87VQ#/screens/409306857

Notes: 
![image](https://user-images.githubusercontent.com/37560480/110733252-76bec700-81da-11eb-94a5-22eca5c7572e.png)

**Comment by hawkticehurst** [comment]
This component library uses [Mozilla Protocol](https://protocol.mozilla.org/) styling so please reference their documentation as this component is being developed. Feel free to literally copy and paste one of the templates that fit closest to the UX notes and then adapt it from there.

_A Caveat_: Mozilla Protocol does not seem to provide styling for a table component as far as I can tell, so to whoever develops this component, do your best to use Mozilla styling where you can but you will likely have to be a bit more custom in this implementation.

@tohuynh @JacksonMaxfield Any additional thoughts on the implementation of this component given the circumstances?

**Comment by JacksonMaxfield** [comment]
Icons should probably be from https://heroicons.com/

Other than that. Nothing else! Thanks for the additional comments @hawkticehurst

**Comment by JacksonMaxfield** [comment]
Closed by #43
