### ISSUE TITLE
Meeting's votes table

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#34]
This is a table summarising the voting that took place during a meeting:
![image](https://user-images.githubusercontent.com/37560480/110734073-eda88f80-81db-11eb-9821-7a1414e8d982.png)

There isn't a design from the UX team for this yet, but use the design for [council member's voting records table](https://github.com/CouncilDataProject/cdp-frontend/issues/33) as guidelines.

**Comment by hawkticehurst** [comment]
This component library uses Mozilla Protocol styling so please reference their documentation as this component is being developed. Feel free to literally copy and paste one of the templates that fit closest to the UX notes and then adapt it from there.

_A Caveat_: Mozilla Protocol does not seem to provide styling for a table component as far as I can tell, so to whoever develops this component, do your best to use Mozilla styling where you can but you will likely have to be a bit more custom in this implementation.

@tohuynh @JacksonMaxfield Any additional thoughts on the implementation of this component given the circumstances?

**Comment by JacksonMaxfield** [comment]
Nothing else from me. Thanks @hawkticehurst for extra info!

**Comment by tohuynh** [comment]
I can take this one.

**Comment by JacksonMaxfield** [comment]
I think Brian was on this one already. May want to wait until tonight @tohuynh to discuss with him progress.

**Comment by BrianL3** [comment]
I just put out the council member's voting records table PR.  Once that gets picked over and merged, I will pick this up since they are very similar.
