### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#36]
Simple! Add a footer component:

![image](https://user-images.githubusercontent.com/17132317/110734780-5e03e080-81dd-11eb-943e-99e693a39e80.png)

Some differences from the design above. The component should accept an object that has a mapping of link name to url. This is to make it possible for each CDP instance to have semi-custom footers.

In that way, it is a _bit_ more like the currently live footer: 
![image](https://user-images.githubusercontent.com/17132317/110734902-999eaa80-81dd-11eb-8c57-dcc1ca635b42.png)

The only links that should always be present and are always defined are:
* CouncilDataProject information -> links to [councildataproject.github.io](councildataproject.github.io)
* CouncilDataProject github -> links to [github.com/councildataproject](github.com/councildataproject)
* The instances github -> links to `github.com/their-org/their-repo`

The only text that should always be there is the disclaimer text:

* "Transparency and accessibility in council action."
* "Meeting transcript accuracy varies and may not always represent what was said."

**Comment by JacksonMaxfield** [comment]
@tohuynh @hawkticehurst have thoughts on how to phrase the "transcript accuracy" text?

**Comment by hawkticehurst** [comment]
This component library uses [Mozilla Protocol](https://protocol.mozilla.org/) styling so please reference their documentation as this component is being developed. Feel free to literally copy and paste one of the templates that fit closest to the UX notes and then adapt it from there.

Mozilla Protocol Footer: https://protocol.mozilla.org/patterns/organisms/footer.html
