### ISSUE TITLE
Council Member Details Page

### ISSUE THREAD

**Issue by hawkticehurst** [CouncilDataProject/cdp-frontend#38]
**Note: This is a bigger issue that could be split up and shared by multiple people**

Based on the UX research [recommendations](https://docs.google.com/presentation/d/15rkic20QV6GU0_nL-8zHIgcw8-o1bCQIiYMsY2j6qFg/edit#slide=id.g8c29f09c95_0_95) implement the necessary components to build out a Council Member Details Page! 

![image](https://user-images.githubusercontent.com/39639992/110743034-408a4300-81ec-11eb-88e7-957041447e65.png)

A Short List Of Components:
- Page Title Component
- Map Banner Component
- Profile Picture Component
- Council Member Bio Component
- Social Card (or Link) Components
- Contact Info Component
- Finally, an overall Council Member Details Page component to bring all of the above together

@JacksonMaxfield @tohuynh Any additional thoughts and comments?

**Comment by JacksonMaxfield** [comment]
Hold off on this for a bit. Still needs thinking and design ideation / determining how easy bits of content are to expose.

**Comment by tohuynh** [comment]
Just a thought, some mention of the voting records table should be initially visible (even if clicking on it just scrolls down to the table).

**Comment by JacksonMaxfield** [comment]
Closing this in favor of the more heavily documented #60
