### ISSUE TITLE
Legislation card

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#4]
Related to  [#79](https://github.com/CouncilDataProject/seattle/issues/79).
Write a legislation card component and update the styling to match the UX team's designs.

**Comment by JacksonMaxfield** [comment]
See example: 
![image](https://user-images.githubusercontent.com/17132317/99860739-cfddee80-2b48-11eb-9479-f75d9ae88c4c.png)

From: https://projects.invisionapp.com/share/UGW7LLV87VQ#/screens/407317061

**Comment by tohuynh** [comment]
I can take this one using Mozilla protocol
