### ISSUE TITLE
Navigational Locationalization

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#48]
## Use Case
*Please provide a use case to help us understand your request in context*

While event, legislation, and council member content is a larger scale project, setting up localization for navigation and components would be nice. Enable more users to at least navigate the site.

## Solution
*Please describe your ideal solution*

Seems like `react-localization` would be good. We just need to define all the strings we use and then it will swap them all out for us.

https://www.npmjs.com/package/react-localization

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by BrianL3** [comment]
Pulling this for the July hackathon.  Going with the ```react-localization``` route and replacing all the strings.
