### ISSUE TITLE
Council member card

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#5]
Related to  [#79](https://github.com/CouncilDataProject/seattle/issues/79).
Write a council member card component and update the styling to match the UX team's designs.

**Comment by JacksonMaxfield** [comment]
Example: 
![image](https://user-images.githubusercontent.com/17132317/99860880-4ed32700-2b49-11eb-9c11-84747ae7d1a2.png)

**Comment by tohuynh** [comment]
@JacksonMaxfield  Wanna get rid of the person name overlay and move it between the image and the district description?

**Comment by JacksonMaxfield** [comment]
> @JacksonMaxfield Wanna get rid of the person name overlay and move it between the image and the district description?

Yep!
