### ISSUE TITLE
Mobile-friendly Tables

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#55]
## Use Case
All tables in the project are currently bog-standard HTML, and make no reference to screen size.  If viewed on small screens, they become ugly-at-best, unusable-at-worst. 

## Solution
Probably turn the tables into cards of some sort. In reality, look up what the best practices are for mobile tables and... do that.

## Alternatives
I have no alternatives, go wild.

**Comment by JacksonMaxfield** [comment]
Resolved in #63
