### ISSUE TITLE
[f_legislationtracking] Design & Web App: Legislation Page

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#56]
## Use Case
There have been request(s) for a way of looking at a bill and seeing its legislative history, e.g. various amendments, votes, etc.  This would be really cool, and our data model could support it (although it is not currently being scraped). 

## Solutions:
Some sort of tree visualization.  
For inspiration, check this out: [Washington State Bills from Legex](http://www.legex.org/wa/process)  Probably a bit more than we need but interesting, especially if we have a very detailed history of the bills that includes the various meetings where they have been discussed, public comment periods, etc. 

A potential library for _creating_ such visualizations: https://airbnb.io/visx/dendrograms

Please post other visions of what this might look like in the comments.

**Comment by JacksonMaxfield** [comment]
@BrianL3 added low priority because we dont have a legislation page design yet and this is where that would go. if we have the time I would REALLY love to get this in though but prioritize last

**Comment by tohuynh** [comment]
Legislation page component requirements:
#172 
#173 
#174 
#175

**Comment by tohuynh** [comment]
Data requirements for the page:
- Get the matter/legislation given the matter id. `matter.name` is the title of the page, while `matter.title` is the long description of the matter.
- Get the sponsors by querying `MatterSponsor` given the matter id
- Get the timeline of the matter by querying for `MatterStatus` give the the matter id. They should be sorted by `matterstatus.update_datetime` in `desc`.
- The latest MatterStatus will provide information about the matter's status and last updated datetime
- Use the latest MatterStatus to find the last event information. Use `latest_matterstatus.event_minutes_item.event_ref`
- To get the votes for a timeline item, use the matterstatus.event_minutes_item_ref to query for `Votes`. Or query for `Votes` using   the matter id, and then assemble the votes for each `MatterStatus` by using matterstatus.event_minutes_item_ref as a pivot.
- To get the attachments of a timeline item, use the matterstatus.event_minutes_item_ref to query for `EventMinutesItemFiles`
- Missing data: timeline item description (e.g. "city clerk sent for review", "council president office sent for review" etc). This information is not in `MatterStatus` nor `EventMinutesItem`.

@JacksonMaxfield Am I missing anything?

**Comment by tohuynh** [comment]
Page's "time to interactivity" consideration: the page should render after the "necessary" information has been loaded.
What would be the necessary information, everything except the timeline component?

**Comment by JacksonMaxfield** [comment]
First, this is an amazing write up. Thank you for doing this.

> Missing data: timeline item description (e.g. "city clerk sent for review", "council president office sent for review" etc). This information is not in MatterStatus nor EventMinutesItem

Totally correct. For now our matter timelines will only reference events for the most part. But this is what I was talking about here: http://councildataproject.org/self/#/events/8ce513a84175?s=0&t=1613

If we get a metadata ingestion pipeline written then we may have more of this info which would be huge. (cc @dphoria)

>> Page's "time to interactivity" consideration: the page should render after the "necessary" information has been fetched.
>>
> What would be the necessary information, everything except the timeline component?

Yep. The timeline / history component should be accordian up / hidden on page load and the actual extra data should be loaded in the background.

**Comment by JacksonMaxfield** [comment]
From meeting: let's try to deploy this feature sooner rather than later!

Let's deploy the all legislation page and the single legislation page without search and keywords.

We can add search and keywords later whenever the matter index pipeline is finished.
