### ISSUE TITLE
Event Meetings (and Search) Containers

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#57]
Create the Event Meetings Container and Search variant

The "raw" event meetings container is basically this page:
https://councildataproject.github.io/seattle/#/events
![image](https://user-images.githubusercontent.com/17132317/122327105-30b48600-cee2-11eb-8687-5bd0ff47819a.png)

But for v3 there are changes:
* Use the new Event Card Component
* Use the new Filter and Sort components
* Add the search bar that will simply re-route to the searched events page and with the same filter and sort state
* Maybe update the styling of the page selection to try to match mozilla protocol

The "searched" event meetings container is this page:
https://councildataproject.github.io/seattle/#/search?q=housing
![image](https://user-images.githubusercontent.com/17132317/122327491-ca7c3300-cee2-11eb-911f-6ca53041594a.png)

With all the same details as above for v3 changes.

**Comment by JacksonMaxfield** [comment]
Actually considering I think the search bar should always be showing, I think this is really just one container! Yay!

**Comment by tohuynh** [comment]
Will work on the `/events` page/container.
