### ISSUE TITLE
Minutes & Documents container

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#6]
See this: https://projects.invisionapp.com/share/UGW7LLV87VQ#/screens/407317058
Related to: [#78](https://github.com/CouncilDataProject/seattle/issues/78)

**Comment by JacksonMaxfield** [comment]
Example:
![image](https://user-images.githubusercontent.com/17132317/99860940-7cb86b80-2b49-11eb-9fff-a5c487d627ae.png)

**Comment by JacksonMaxfield** [comment]
This is the container object around #35

**Comment by BrianL3** [comment]
I'm going to pull this and call it MeetingDetailsContainer, if there are no objections.

**Comment by JacksonMaxfield** [comment]
I think the two components of this are done. Going to close because about to open the "event container" issue.
