### ISSUE TITLE
NPM Warning: "Unsupported Engine"

### ISSUE THREAD

**Issue by hawkticehurst** [CouncilDataProject/cdp-frontend#68]
## System and Software
* Operating System: macOS
* Web Browser: Chrome

## Page or Route
N/A

## Description
I just did a fresh clone/npm install of `cdp-frontend` and got an NPM `EBADENGINE` warning. Not sure what level of a priority this warning is but thought I should note it.

## Notes
<img width="632" alt="Screen Shot 2021-07-14 at 10 48 10 PM" src="https://user-images.githubusercontent.com/39639992/125735754-8325dd82-c24a-4bed-9daa-005f3bc6a490.png">

**Comment by JacksonMaxfield** [comment]
We can probably upgrade to node 14 I would suspect?

**Comment by tohuynh** [comment]
It just that in package.json it uses 12.x, but you have 14.x. You can use node manager of some sort to switch versions.

**Comment by hawkticehurst** [comment]
Okay, cool. Do we want to take this opportunity to update the required engine since 14 is now the latest stable version of Node or meh?

**Comment by tohuynh** [comment]
It's good to stay up-to-date on node version. I don't know if we should update the engine before we finished our milestone though. Regardless, I think it's low priority.

Btw, I use [nvm](https://github.com/nvm-sh/nvm) for using different node versions.

**Comment by hawkticehurst** [comment]
Sweet, sounds good to me. And lol yeah me too––although I use it so infrequently I forgot what it was called to thank you for saving me a google search 😂
