### ISSUE TITLE
Plain text query function

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-frontend#79]
Impliment the same or similar search query as found in [cdp-backend: `search_cdp_events`](https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/bin/search_cdp_events.py#L129)

This will be used populate the ManyEvent Container / page.

@tohuynh what information do you think is enough for this to return with.

```json
{
    "event_id": "...",
    "event_datetime": "...",
    "event_pure_relevance": "...",
    "event_datetime_weighted_relevance": "...",
    "event_contained_grams": "...",
    "event_context_span": "..."
}
```

Or would you like more?

**Comment by tohuynh** [comment]
These search results are the event/meeting cards right? Then you'd need a picture of the event, body's name, and tags as well. https://councildataproject.org/cdp-frontend/?path=/story/library-cards-events--meeting

You can implement this search in the EventService I'm currently working on. https://github.com/tohuynh/cdp-frontend/blob/feature/networking/src/networking/EventService.ts

or Write it in SearchEventService.ts (I like this more).

**Comment by JacksonMaxfield** [comment]
Sounds good. I will get to this probably next week ish.
