### ISSUE TITLE
Add routing/navigation to app

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#87]
### Feature Description

Add routing to the app using [react-router-dom](https://reactrouter.com/web/guides/quick-start)

#### v3 goals
routes:
`/events/:id`
`/events` (events sorted by recency)
`/persons/:id`
`/persons`
`/` "home page"
`/search`

@JacksonMaxfield, anything missing ?
### Solution

_Please describe your ideal solution._

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

### Screenshots/References

_In the case of a visually oriented feature or component request, providing drawings, screenshots, and/or links to examples of what you're seeking will be very helpful._

**Comment by JacksonMaxfield** [comment]
`/events` unless you are considering search to be that. Which I can see. I think I would rather have it be called events personally

**Comment by JacksonMaxfield** [comment]
Well... Hmmm. How are we going to add matter search in the future... Maybe `/search` _is_ better as we can add more results to it regardless of events or not...

**Comment by JacksonMaxfield** [comment]
Or both

**Comment by tohuynh** [comment]
Yeah I was using `/search?q=query` to contain the search results (events, matters, and/or persons)

**Comment by JacksonMaxfield** [comment]
I would still add one for just events. We can add custom styling to it like "latest event" as a banner and such. More routes is nice imo
